---
title: "ESA Listings Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    css: custom.css
    social: menu
    df_print: paged
    navbar:
    - {title: "CCI", align: right, href: "https://defenders-cci.org"}
    - {title: "", icon: "fa-question-circle fa-lg", align: right, href: "mailto:jmalcom@defenders.org?subject=ESA listings dashboard"}
    - {title: "", icon: "fa-github fa-lg", align: right, href: "https://github.com/Defenders-CCI/"}
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(lubridate)
library(plotly)
library(shiny)
library(shinydashboard)
library(tidyverse)

dat <- readRDS("ESA_listings.rds")
names(dat) <- c("common", "scientific", "status", "entity", "listing_date", "taxon",
                "region")
dat$listing_date <- mdy(dat$listing_date)
dat$listing_year <- year(dat$listing_date)

# This is for one NOAA species that has no date...
dat$listing_year <- ifelse(is.na(dat$listing_year),
                           2016,
                           dat$listing_year)

t1 <- table(dat$listing_year, dat$taxon) %>% as.data.frame()
```


Filters {.sidebar}
-----------------------------------------------------

### Filters

```{r filters, echo=FALSE}
status <- c("All", unique(dat$status) %>% sort(decreasing = FALSE))
regions <- c("All", unique(dat$region) %>% sort(decreasing = FALSE))

selectInput(
  "status1",
  "Status",
  status
)

selectInput(
  "region1",
  "Region",
  regions
)
```

```{r filtering, echo=FALSE}
usr_sel <- function(df, st, re) {
  if(st != "All") {
    df <- filter(df, df$status == st)
  }
  if(re != "All") {
    df <- filter(df, df$region == re)
  }
  if(dim(df)[1] == 0) stop("No data matches.")
  return(df)
}

sel <- reactive({
  usr_sel(dat, input$status1, input$region1)
})

```

### Background

The Endangered Species Act protects species in danger of extinction (Endangered) or likely to become endangered (Threatened). This small dashboard illustrated how listings have changed over time based on the [data service from the U.S. Fish and Wildlife Service](https://ecos.fws.gov/ecp/report/ad-hoc-documentation?catalogId=species&reportId=species), updated daily. 

Row {data-height=750}
-----------------------------------------------------

### ESA listings by taxonomic group, through time

```{r fig1, echo=FALSE}
renderPlotly({
  
  t2 <- lapply(seq(min(dat$listing_year), max(dat$listing_year), 1), 
               FUN = function(x) {
                 tmp <- filter(sel(), sel()$listing_year <= x)
                 a <- table(tmp$taxon) %>% as.data.frame(stringsAsFactors = FALSE)
                 year <- rep(x, length(a[[1]]))
                 a <- cbind(a, year)
  })
  t3 <- bind_rows(t2)
  names(t3) <- c("taxon", "n_spp", "year")

  plot_ly(data = t3, x = ~year, y = ~n_spp, color = ~taxon, type = "bar") %>%
    layout(yaxis = list(title = "Number of species"),
           xaxis = list(title = ""),
           barmode = "stack")
})
```

Row {data-height=150}
-------------------------------------------------------------
### {.value-box}

```{r info1, echo=FALSE}
flexdashboard::renderValueBox({
  flexdashboard::valueBox(
    caption = "Number of ESA-Listed Species",
    value = nrow(sel()),
    color = "info"
  )
})
```

### {.value-box}

```{r}
flexdashboard::renderValueBox({
  flexdashboard::valueBox(
    caption = "Number of Threatened Species",
    value = nrow(filter(sel(), sel()$status == "Threatened")),
    color = "warning"
  )
})
```

### {.value-box}

```{r}
flexdashboard::renderValueBox({
  flexdashboard::valueBox(
    caption = "Number of Endangered Species",
    value = nrow(filter(sel(), sel()$status == "Endangered")),
    color = "danger"
  )
})
```


